src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
class Order
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'datetime')]
    private $createdAt;

    #[ORM\Column(type: 'integer')]
    private $nb_products;

    #[ORM\Column(type: 'float')]
    private $total_account;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'orders')]
    #[ORM\JoinColumn(onDelete: "CASCADE")]
    private $user;

    #[ORM\Column(type: 'boolean', nullable: true)]
    private $status;

    #[ORM\OneToMany(mappedBy: 'order', targetEntity: OrderItems::class, cascade: ["persist"])]
    #[ORM\JoinColumn(onDelete: "CASCADE")]
    private $items;

    #[ORM\Column(type: 'string', length: 255)]
    private $address;

    #[ORM\Column(type: 'string', length: 255)]
    private $zipcode;

    #[ORM\Column(type: 'string', length: 255)]
    private $city;


    public function __construct()
    {
        $this->createdAt = new DateTime();
        $this->status = false;
        $this->items = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getNbProducts(): ?int
    {
        return $this->nb_products;
    }

    public function setNbProducts(int $nb_products): self
    {
        $this->nb_products = $nb_products;

        return $this;
    }

    public function getTotalAccount(): ?float
    {
        return $this->total_account;
    }

    public function setTotalAccount(float $total_account): self
    {
        $this->total_account = $total_account;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getStatus(): ?bool
    {
        return $this->status;
    }

    public function setStatus(?bool $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getZipcode(): ?string
    {
        return $this->zipcode;
    }

    public function setZipcode(string $zipcode): self
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * @return Collection|OrderItems[]
     */
    public function getItems(): Collection
    {
        return $this->items;
    }


    public function addItem(OrderItems $item): self
    {
        if (!$this->items->contains($item)) {
            $this->items[] = $item;
            $item->setOrderId($this);
        }

        return $this;
    }

    public function removeItem(OrderItems $item): self
    {
        if ($this->items->removeElement($item)) {
            // set the owning side to null (unless already changed)
            if ($item->getOrderId() === $this) {
                $item->setOrderId(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @UniqueEntity(fields={"email"}, message="Il y a déjà un compte avec cet email.")
 */
#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 180, unique: true)]
    private $email;

    #[ORM\Column(type: 'json')]
    private $roles = [];

    #[ORM\Column(type: 'string')]
    private $password;

    #[ORM\Column(type: 'string', length: 255)]
    private $firstname;

    #[ORM\Column(type: 'string', length: 255)]
    private $lastname;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $address;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $zipcode;

    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $city;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Order::class)]
    private $orders;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Comment::class)]
    private $comments;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Contact::class)]
    private $contacts;

    public function __construct()
    {
        $this->orders = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->contacts = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = ucfirst($firstname);

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = ucfirst($lastname);

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = ucfirst($address);

        return $this;
    }

    public function getZipcode(): ?string
    {
        return $this->zipcode;
    }

    public function setZipcode(?string $zipcode): self
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = ucfirst($city);

        return $this;
    }

    /**
     * @return Collection|Order[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->setUser($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getUser() === $this) {
                $order->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getUser() === $this) {
                $comment->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Contact[]
     */
    public function getContacts(): Collection
    {
        return $this->contacts;
    }

    public function addContact(Contact $contact): self
    {
        if (!$this->contacts->contains($contact)) {
            $this->contacts[] = $contact;
            $contact->setUser($this);
        }

        return $this;
    }

    public function removeContact(Contact $contact): self
    {
        if ($this->contacts->removeElement($contact)) {
            // set the owning side to null (unless already changed)
            if ($contact->getUser() === $this) {
                $contact->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Order;
use App\Form\AccountType;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use App\Service\Alert\AlertServiceInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

class UserController extends AbstractController
{

    #[Route('/users/profile/', name: 'user_profile')]
    /**
     *  @IsGranted("ROLE_USER")
     */
    public function profile(ManagerRegistry $doctrine): Response
    {
        $user = $this->getUser();
        $orders = $doctrine->getRepository(Order::class)->findAll();

        return $this->render('users/user_profile.html.twig', [
            'user' => $user,
            'orders' => $orders,
        ]);
    }

    #[Route('/users/profile_edit', name: 'profile_edit')]
    /**
     *@IsGranted("ROLE_USER")
     */
    public function EditProfile(Request $request, EntityManagerInterface $manager, AlertServiceInterface $alert)
    {
        // getUser : personne déjà connectée

        $user = $this->getUser();
        $form = $this->createForm(AccountType::class, $user);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {
            $manager->persist($user);
            $manager->flush();
            $alert->success("Vos informations ont bien été modifiées");

            return $this->redirectToRoute('user_profile');
        }
        return $this->render('users/profile_edit.html.twig', [
            'profileForm' => $form->createView(),

        ]);
        return $this->render('users/user_profile.html.twig');
    }

    #[Route('users/show_order/{id}', name: 'see_order')]
    /**
     * @Security("user === order.getUser()", message = "Cette commande ne vous appartient pas")
     */
    public function seeOrder(Order $order): Response
    {
        return $this->render('/users/order_detail.html.twig', [
            'order' => $order
        ]);
    }
}

templates/users/_add_comment.html.twig
{% extends "base.html.twig" %}

{% block title %}Ajouter un commentaire
{% endblock %}

{% block body %}

	<div class="container mt-5 mb-5">


		<div class="col-md-6 p-5 shadow rounded offset-md-3">
			<h1 class="h2 mb-5">Ajouter un commentaire</h1>
			{{form_start(commentForm)}}
			{{form_widget(commentForm)}}
			<div class="d-flex justify-content-between">
				<a href="{{path('home')}}#homeComment" class="btn btn-dark">
					<i class="fas fa-backward"></i>
					Retour</a>
				<button type="submit" class="btn btn-primary">Ajouter</button>
				{{form_end(commentForm)}}
			</div>
		</div>
	</div>
</div>{% endblock %}

templates/users/order_detail.html.twig
{% extends "base.html.twig" %}

{% block title %}{% endblock %}

{% block body %}
	<div class="container mt-5 mb-5">

		{% if is_granted('ROLE_ADMIN') %}
			<h1>Détail de la commande N°
				{{order.id}}</h1><br>
		{% else %}
			<h1>Détail de votre commande N°
				{{order.id}}</h1><br>
		{% endif %}

		<p>Livrée à :
			{{order.user.lastname}}
			{{order.user.firstname}},
			{{order.address}},
			{{order.zipcode}},
			{{order.city}}</p>

		<table class="table table-striped">
			<thead>
				<th>Produit</th>
				<th>Prix</th>
				<th>Quantité</th>
				<th>Total</th>
			</thead>
			<tbody>
				{% for item in order.items %}
					<tr>
						<td>{{item.food.name}}</td>
						<td>{{item.food.price}}
							&euro;</td>
						<td>{{item.quantity}}</td>
						<td>{{item.quantity * item.food.price }}
							&euro;</td>
					</tr>
				{% endfor %}
			</tbody>

			<tfoot>
				<tr class="bg-secondary text-white fw-bold">
					<td colspan="3">Total de la commande</td>
					<td>{{order.totalAccount / 100}}
						&euro;</td>
				</tr>
			</tfoot>
		</table>
		{% if is_granted('ROLE_ADMIN') %}
			<a class="btn btn-dark" href="{{path('show_orders')}}">
				<i class="fas fa-backward"></i>
				Retour</a>
		{% else %}
			<a class="btn btn-dark" href="{{path('user_profile')}}">
				<i class="fas fa-backward"></i>
				Retour</a>
		{% endif %}
	</div>

{% endblock %}

templates/users/profile_edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification du profil
{% endblock %}

{% block body %}


	<div class="container mt-5 mb-5">
		<div class="row align-items-center">
			<div class="col-md-6 offset-md-3 shadow bg-light p-5">
				<h2 class="text-center bg-light mb-4">Modification de votre profil</h2>
				<hr>
				{{form_start(profileForm)}}
				{{form_widget(profileForm)}}
				<button type="submit" class="btn btn-primary">Modifier</button>
				<a href="{{path('user_profile')}}" class="btn btn-dark">
					<i class="fas fa-backward"></i> Retour</a>
				{{form_end(profileForm)}}
			</div>
		</div>
	</div>

{% endblock %}

templates/users/user_profile.html.twig
{% extends "base.html.twig" %}

{% block stylesheets %}
	<link rel="stylesheet" type="text/css" href="/css/datatables.min.css"/>
{% endblock %}

{% block body %}

	<section id="bloc-titre-user" class="d-flex justify-content-center">
		<h1 class="text-white align-self-center">Votre profil</h1>
	</section>

	<div class="container mt-5 mb-5">

		<div class="row">

			<div class="col-md-4 mb-5">
				<div class="rounded shadow p-4">
					<h3 class="text-center">Vos informations</h3><hr>
					<dl class="row">
						<dt class="col-md-4">Nom:</dt>
						<dd class="col-md-8">{{app.user.firstname}}</dd>
						<dt class="col-md-4">Prénom:</dt>
						<dd class="col-md-8">{{app.user.lastname}}</dd>
						<dt class="col-md-4">Email:</dt>
						<dd class="col-md-8">{{app.user.email}}</dd>
						<dt class="col-md-4">Adresse:</dt>
						<dd class="col-md-8">
							{% if app.user.address %}
								{{app.user.address}},
								{{app.user.zipcode}},
								{{app.user.city}}
							{% else %}
								<a href="{{path('profile_edit')}}">Ajouter votre adresse</a>
							{% endif %}
						</dd>
					</dl>
					<a href="{{path('profile_edit')}}" class="mt-3 btn btn-primary form-control">Modifier vos informations</a>
				</div>
			</div>

			<div class="col-md-8 p-4">
				<h3 class="text-center">Vos commandes</h3><hr>
				{% if app.user.orders %}
					<table class="table table-striped" id="userOrderTable">
						<thead>
							<th>Commande n°</th>
							<th>Le</th>
							<th>Total</th>
							<th>Détails</th>
						</thead>

						{% for order in user.orders %}
							<tr>
								<td>{{order.id}}</td>
								<td>{{order.createdAt|date('d-m-y')}}
									à
									{{order.createdAt|date('H:i')}}</td>
								<td>{{(order.totalAccount)/100}}
									&euro;</td>
								<td>
									<a href="{{path('see_order',{'id':order.id})}}" class="btn btn-sm btn-dark">
										<i class="fas fa-eye"></i>
									</a>
								</td>
							</tr>
						{% endfor %}
					</table>


				{% else %}
					<div class="alert alert-info">Vous n'avez pas encore de commandes</div>
				{% endif %}

			</div>
		</div>
	</div>
{% endblock %}

{% block javascripts %}
	<script src="/js/datatables.min.js"></script>
	<script src="/js/tables.js"></script>
{% endblock %}